name: Run code blocks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  run-code-blocks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      # https://github.com/mikkelricky/markdown-code-runner
      - run: |
          go run github.com/mikkelricky/markdown-code-runner@latest run \
            --verbose --echo '👉 ' \
            development-install coding-standards-composer
